
#this is a comment
#test2

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: be my pen pal
description: i miss my homies so i write to them
